### PR TITLE
Reorganize spec-folder

### PR DESCRIPTION
**Pull request by teoljungberg**
Try to map `lib/foo/bar.rb` to `spec/foo/bar_spec.rb`

### CODE REVIEW

**Comment by henrik** [comment]
Sounds good! Any particular reason – does this work better with some specific tool, for example?

**Comment by henrik** [comment]
Thank you!

**Comment by teoljungberg** [comment]
It makes tools that toggle between implementation and test work, i.e `vim-rake` in this case

**Comment by henrik** [comment]
Cool. I use Rails.vim for that kind of toggling in Rails projects. Will look into vim-rake.

**Pull request merged**
